### ISSUE TITLE
Difference between bezier, one, semi, LR and full

### ISSUE THREAD

**Issue by grupot3** [pgousenbourg/manint#1]
Hi,

Thanks for releasing this code. I have one question: what is exactly the role of the "reconstruction" field of the `problem` structure? In other words, what's the difference between `bezier`, `one`, `semi`, `LR` and `full` in [these lines](https://github.com/pgousenbourg/manint/blob/master/methods/curves/cp_approx.m#L155-L159)?

I've tried to change `LR` to `full` and run `curveFittingSphere`, and the curve produced seems the same one (at least visually)

Thanks!

**Comment by pgousenbourg** [comment]
Hi !
Thank you for your message !
The fonction cp_approx permits to compute control points (cp) that will later be used in the reconstruction process.
The field "reconstruction" was historically used to generate the necessary control points to different reconstruction processes (which are described in [this paper](https://link.springer.com/article/10.1007%2Fs10851-018-0865-2)). It has no purpose anymore. I should remove this field some day ;-).
So it is normal that you get the same result :-).
Best !
